eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:8080/eureka/
    instance:
        prefer-ip-address: true
server:
    port: 9011
spring:
    application:
        name: apigateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
